### ISSUE TITLE
Add support for enabling httparty debug output without changing pvoutput

### ISSUE THREAD

**Issue by jwillemsen** [johnf/pvoutput#11]
Would be nice when we could enable the debugoutput of httparty as used by pvoutput without changing the code at https://github.com/johnf/pvoutput/blob/c3a1574c0de5c7ddfc6edacba09548e6c01b82fc/lib/pvoutput/client.rb#L7

**Comment by johnf** [comment]
What do you think would work better
* New argument to initialize
* an enable_debug method
* enable debugging if an DEBUG=pvoutput:* env variable is set?

**Comment by jwillemsen** [comment]
Initially I thought about a new argument to initialize, but that would require that each using gem needs support that, for users maybe the easiest to add support for a new environment variable (PVOUTPUT_DEBUG?) that enabled debugging, that is the easiest for users, nobody needs to adapt their code and they just enable a environment variable and can see what is happening.

**Comment by johnf** [comment]
Done in 727fc363b2c299a1105ebe6a2d8ffb8d193c4805 and released in 0.5.0
