### ISSUE TITLE
Helping maintain

### ISSUE THREAD

**Issue by johnf** [johnf/pvoutput#14]
@jwillemsen would you be interested in having merge access
My thinking I set up repo so we both need to review pull requests, prevenbt push to master etc
I'll also set up github actions to auto deploy on new version tag to rubygems

**Comment by jwillemsen** [comment]
Yes, interested in that.

**Comment by jwillemsen** [comment]
In our r2corba repo we have an action for the deploy, see https://github.com/RemedyIT/r2corba/blob/master/.github/workflows/gem_release.yml

**Comment by johnf** [comment]
Great I'll look at setting something up over the weekend

**Comment by johnf** [comment]
@jwillemsen  I've added you as a collaborator.

**Comment by jwillemsen** [comment]
Thanks, looks we can close this one now
