### ISSUE TITLE
Enable discussions?

### ISSUE THREAD

**Issue by jwillemsen** [johnf/pvoutput#28]
Hi John, could you enable discussions in the project settings? Shall I prepare a new release? Not sure whether I have all permissions for a new 1.1 release

**Comment by johnf** [comment]
Done. Can you give try following the release process and see if it will let you. I think it should.

**Comment by jwillemsen** [comment]
Do we want a branch for the release? Looks there is none for v100,  the changes to readme and version do have to appear on master

**Comment by johnf** [comment]
I think the same PR process we've been using with the commits to set version etc

**Comment by jwillemsen** [comment]
Yes, all worked, Thanks!
